version: '3.7' # specify docker-compose version (docker -v)

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    networks:
      - host
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - host

  web:
    image: escobarana/smartcarapi:latest
    container_name: web
    environment:
      ENVIRONMENT: PRODUCTION
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      FLASK_DEBUG: False
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - host
    volumes:
      - .:/code

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - web
    ports:
      - "9090:9090"
    networks:
      - host
    volumes:
      - "./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - host
    volumes:
      - ./monitoring/grafana/config.ini:/etc/grafana/grafana.ini
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yml
      - ./monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

networks:
    host: