name: Build and push Docker image to Docker Hub
on:
  workflow_run:  # Dependency between workflows
    workflows: [ "Python CI" ]
      branches:
        - '*'
      types:
        - completed

jobs:
  push_to_registry:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Triggers only if dependent workflow is successful
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: |
              ${{ secrets.DOCKERHUB_USERNAME }}/smartcarapi

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smartcarapi:latest
