name: Python CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]  # Using local settings
        mongodb-version: [ '6.0' ]  # Using local settings
#    defaults:
#      run:
#        working-directory: smart_carapi

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install requirements
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #- name: Append to PATH
      #  run: echo "/devops-smart-car" >> $GITHUB_PATH
      - name: Run Tests with unittest
        run: python -m unittest smart_carapi/tests/__init__.py
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"