name: Python CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./smart_carapi
    strategy:
      matrix:
        python-version: [ 3.8 ]  # Using local settings
        mongodb-version: [ '6.0' ]  # Using local settings

    env:
      ENVIRONMENT: LOCAL
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests with unittest
        run: python -m unittest tests/__init__.py
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"